#!/bin/bash
DIR=$(dirname "$0")
clear
cd $DIR

#!/bin/bash

pkgbuild --root package-root \
         --identifier uk.insoft.pplref \
         --version 1.0 --install-location / \
         --scripts scripts \
         pplref.pkg
 

read -p "Press Enter to exit!"

# Close the Terminal window
osascript -e 'tell application "Terminal" to close window 1' & exit
